#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
mvn -f $OPENSHIFT_REPO_DIR/pom.xml clean install -Dmaven.repo.local=$OPENSHIFT_DATA_DIR/repository
